### ISSUE TITLE
fatal error: runtime.SetFinalizer: cannot pass *tsm.Screen to finalizer func(*tsm.VTE)

### ISSUE THREAD

**Issue by aaronjanse** [emersion/go-tsm#2]
Thanks for writing go-tsm. I plan on using it for a few of my projects.

While trying to setup some demo code so I can learn how to use your library, I ran into the following error, and cannot seem to get past it:

```
fatal error: runtime.SetFinalizer: cannot pass *tsm.Screen to finalizer func(*tsm.VTE)

goroutine 1 [running]:
runtime.throw(0xc0000c0000, 0x49)
        /nix/store/52w2rhaxsiy68gv7jmmgcam193njlg7j-go-1.11.2/share/go/src/runtime/panic.go:608 +0x72 fp=0xc000058610 sp=0xc0000585e0 pc=0x42b3c2
runtime.SetFinalizer(0x4b8d60, 0xc0000b2018, 0x49b7a0, 0x4c31c0)
        /nix/store/52w2rhaxsiy68gv7jmmgcam193njlg7j-go-1.11.2/share/go/src/runtime/mfinal.go:405 +0x51e fp=0xc0000586f8 sp=0xc000058610 pc=0x418fae
github.com/emersion/go-tsm.NewVTE(0xc0000b2018, 0x4c31e8, 0x1d)
        /home/ajanse/.go/src/github.com/emersion/go-tsm/vte.go:47 +0xe8 fp=0xc000058750 sp=0xc0000586f8 pc=0x48a258
main.main()
        /home/ajanse/.go/src/github.com/aaronduino/testing-go-tsm/main.go:13 +0x37 fp=0xc000058798 sp=0xc000058750 pc=0x48ab17
runtime.main()
        /nix/store/52w2rhaxsiy68gv7jmmgcam193njlg7j-go-1.11.2/share/go/src/runtime/proc.go:201 +0x207 fp=0xc0000587e0 sp=0xc000058798 pc=0x42cd37
runtime.goexit()
        /nix/store/52w2rhaxsiy68gv7jmmgcam193njlg7j-go-1.11.2/share/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000587e8 sp=0xc0000587e0 pc=0x4550f1
exit status 2
```

I installed Go with [Nix](http://nixos.org/nix/), so my library paths are long, but I can state with a fairly high level of certainty that this is not the cause of the issue.

Here's my code:
```go
package main

import (
	"fmt"

	tsm "github.com/emersion/go-tsm"
)

func main() {
	screen := tsm.NewScreen()
	vte := tsm.NewVTE(screen, func(b []byte) {
		fmt.Println(b)
	})

	vte.Input([]byte("Hello\nWorld!"))
}
```

**Comment by aaronjanse** [comment]
I think this might fix the problem:

```diff
diff --git a/vte.go b/vte.go
index db746e8..349b227 100644
--- a/vte.go
+++ b/vte.go
@@ -44,7 +44,7 @@ func NewVTE(s *Screen, f VTEWriteFunc) *VTE {
        if ret != 0 {
                panic("tsm: failed to create VTE")
        }
-       runtime.SetFinalizer(s, func(vte *VTE) {
+       runtime.SetFinalizer(vte, func(vte *VTE) {
                C.tsm_vte_unref(vte.vte)
        })
        return vte
```

With the above patch, I am able to sucessfully call NewVTE and send input to it. I cannot figure out how to create a situation where the VTEWriteFunc passed to NewVTE is called, but I am able to print input using screen.Draw

**Comment by emersion** [comment]
Can you send a pull request?

Sorry, I haven't really had the chance to test this package.
